{% set name = "skops" %}
{% set version = "0.12.0" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/skops-dev/skops/archive/v{{ version }}.tar.gz
  sha256: 4368d56609632858c3aa286948b6cfcba30e964c667f1d2c933f5c6fa9ac0c36

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.25.0
    - scipy >=1.10.0
    - scikit-learn >=1.2
    - prettytable >=3.9
    - packaging >=17.0

test:
  imports:
    - skops
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: http://github.com/skops-dev/skops
  summary: A set of tools, related to machine learning in production.
  license: MIT
  license_file: LICENSE
  doc_url: http://github.com/skops-dev/skops
  dev_url: http://github.com/skops-dev/skops

extra:
  recipe-maintainers:
    - sugatoray
    # maintainers from upstream repo
    - adrinjalali
